config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  devise_for :users
  
  
  match '/home',     to: 'home#index',             via: 'get, post'
  resources "contacts", only: [:new, :create]
  
  
  #get 'home/index'
  #post 'home/index'
  resources :home, only: [:index, :new, :create]
  
   get '/search' => 'products#search', :as => 'search_page'

  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  
get '/cart/checkout', to: 'orders#new', as: :checkout
patch '/cart/checkout', to: 'orders#create'

end

app/models/category.rb
class Category < ApplicationRecord
     has_many :product_categories
     has_many :products, through: :product_categories
end

app/models/home.rb
class Home < MailForm::Base
   include MailForm::Delivery

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact You",
      :to => "akobelimited@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end
  

app/models/order.rb
class Order < ApplicationRecord
     has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
  belongs_to :product
end

app/models/person.rb
class Person < ApplicationRecord
   
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
     has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart
  
  delegate :sub_total, to: :order 

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_create_by(
      product_id: product_id
    )
    
    
    
    
    order_item.price = product.price
    order_item.quantity = quantity
    
   
    ActiveRecord::Base.transaction do
    order_item.save
    update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
    order.items.destroy(id)
    update_sub_total!
    end
  end
  
  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/orders_controller.rb
# app/controllers/orders_controller.rb

class OrdersController < ApplicationController
  def new
    @order = current_cart.order
  end
   def create
     
    @order = current_cart.order
    
    if @order.update_attributes(order_params.merge(status:'open'))
      session[:cart_token] = nil
      
      flash[:success] = t('flash.order.success')
      redirect_to root_path
    else
      flash.now[:error] = t('flash.order.error_html')
      render :new
    
    end  
     
   end
   

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name,:email,:phone_number, :address, :phone, :message )
  end
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datepicker.rb
def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hprlaptops_helper.rb
module HprlaptopsHelper
   
  
end

app/helpers/itelphones_helper.rb
module ItelphonesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
    
    
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/retrofits_helper.rb
module RetrofitsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/orders/new.html.erb
<br><br><br>
  
    <div class="container">
    <div class="col-sm-3">
        
    </div>
    <div class="col-sm-6">
            <h2>Checkout</h2>

            <%= form_for @order, url: checkout_path do |f| %> 

             <div class="form-group has-success has-feedback">
                <%= f.label :first_name, class: "sr-only" %>
                <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", :required => 'required' %>
              <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>

            <div class="form-group has-success has-feedback">
                <%= f.label :last_name, class: "sr-only" %>                  
                <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", :required => 'required' %>
             <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>
            
            <div class="form-group has-success has-feedback">
                <%= f.label :email, class: "sr-only" %>                  
                <%= f.email_field :email, class: "form-control", placeholder: "Email", :required => 'required' %>
             <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>
            
             <div class="form-group has-success has-feedback">
                <%= f.label :address, class: "sr-only" %>                  
                <%= f.text_field :deliveryaddress, class: "form-control", placeholder: "Address", :required => 'required' %>
             <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>
            
            <div class="form-group has-success has-feedback">
                <%= f.label :phone_number, class: "sr-only" %>                  
                <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone Number", :required => 'required' %>
             <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>
            <div class="g-recaptcha" data-sitekey="6LfYpM4UAAAAAM72CIuIEX2xDs31QIUlocDrCyKo"></div>
            <div class="modal-footer">
                 <%= f.submit 'Checkout',class: "btn btn-primary" %>
                 
            </div>     

                <% end %>
            </div>
           
            
</div>