config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  devise_for :users
  
  
  match '/home',     to: 'home#index',             via: 'get, post'
  resources "contacts", only: [:new, :create]
  
  
  #get 'home/index'
  #post 'home/index'
  resources :home, only: [:index, :new, :create]
  
   get '/search' => 'products#search', :as => 'search_page'

  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  
get '/cart/checkout', to: 'orders#new', as: :checkout
patch '/cart/checkout', to: 'orders#create'

end

app/models/category.rb
class Category < ApplicationRecord
     has_many :product_categories
     has_many :products, through: :product_categories
end

app/models/home.rb
class Home < MailForm::Base
   include MailForm::Delivery

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact You",
      :to => "akobelimited@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end
  

app/models/order.rb
class Order < ApplicationRecord
     has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
  belongs_to :product
end

app/models/person.rb
class Person < ApplicationRecord
   
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
     has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart
  
  delegate :sub_total, to: :order 

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_create_by(
      product_id: product_id
    )
    
    
    
    
    order_item.price = product.price
    order_item.quantity = quantity
    
   
    ActiveRecord::Base.transaction do
    order_item.save
    update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
    order.items.destroy(id)
    update_sub_total!
    end
  end
  
  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    # before_action :find_user_object,except:[:create]
    # invisible_captcha only: [:orders, :products, :order_items, :categories]
    
     def index
         
         @category = Category.find(params[:category_id])
         @products = @category.products.includes(:variants).order(:title)
         # @products = @category.products.order(:title)
     end
     
    

    
    

end    

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datepicker.rb
def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hprlaptops_helper.rb
module HprlaptopsHelper
   
  
end

app/helpers/itelphones_helper.rb
module ItelphonesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
    
    
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/retrofits_helper.rb
module RetrofitsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/products/index.html.erb
<br><br><br>


  
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
   <h3> <li class="breadcrumb-item"><%= link_to "Categories", root_path %> /</li></h3>
     <h3> <li class="breadcrumb-item"><%= @category.title %>/ </li></h3>
   <h3> <li class="breadcrumb-item active" aria-current="page"> Service Providers</li></h3>
    
  </ol>
</nav>


 <div class="card-group" style="margin-botom:10px">
    <div class="container">
     <div class="card-deck">
        <!--<div class="album text-muted">-->
          
              <div class="row">
                 <% @products.each do |product| %>
                  <div class="col-sm-3 col-md-3 col-sm-6">
                 <div class="card card mb-3 style="max-width: 8rem;", class: "mx-auto d-block">
                 <h5 class="card-title  text-center"  style="margin-top: 10px; margin-bottom:-13px;"><%= product.vendor %> <br>(<%= product.speciality %> )</h5>
                   <%= link_to image_tag  product.image, class: "img-responsive img-thumbnail",  class: "h-100 d-inline-block", class: "w-100 p-5" %></a>
                    <h5 class="card-title  text-center"  style="margin-top: -8px margin-bottom:5px;"><%= product.title %> <br>₦(<%= product.price %>)</h5>
                   <div class="row">
                     <div class="col">
                     <%= form_tag order_items_path do %>
                     <%= hidden_field_tag :product_id, product.id %>
                     <h6><p class=" price card-header text-center"><%= number_field_tag :quantity, 1 %></p></h6> 
                    
                     <h6><p class=" price card-header text-center"> <%= submit_tag "Add to Cart" , class: "btn btn-info btn-sm" %>|<%= submit_tag "View Profile" , class: "btn btn-warning btn-sm" %></p></h6>
                     
                   
                  <% end %>
                  </div>
                 </div>
               </div>
             </div>
            <% end %>
   
          </div>
       </div>
      
 

app/views/products/search.html.erb
<h3>Search Result</h3>  

     
       
  