config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  devise_for :users
  
  
  match '/home',     to: 'home#index',             via: 'get, post'
  resources "contacts", only: [:new, :create]
  
  
  #get 'home/index'
  #post 'home/index'
  resources :home, only: [:index, :new, :create]
  
   get '/search' => 'products#search', :as => 'search_page'

  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  
get '/cart/checkout', to: 'orders#new', as: :checkout
patch '/cart/checkout', to: 'orders#create'

end

app/models/category.rb
class Category < ApplicationRecord
     has_many :product_categories
     has_many :products, through: :product_categories
end

app/models/home.rb
class Home < MailForm::Base
   include MailForm::Delivery

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact You",
      :to => "akobelimited@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end
  

app/models/order.rb
class Order < ApplicationRecord
     has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
  belongs_to :product
end

app/models/person.rb
class Person < ApplicationRecord
   
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
     has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart
  
  delegate :sub_total, to: :order 

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_create_by(
      product_id: product_id
    )
    
    
    
    
    order_item.price = product.price
    order_item.quantity = quantity
    
   
    ActiveRecord::Base.transaction do
    order_item.save
    update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
    order.items.destroy(id)
    update_sub_total!
    end
  end
  
  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datepicker.rb
def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hprlaptops_helper.rb
module HprlaptopsHelper
   
  
end

app/helpers/people_helper.rb
module PeopleHelper
    
    
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/retrofits_helper.rb
module RetrofitsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/_breaknews.html.erb
<br>
<hr>

<div class="onoffswitch3">
    <input type="checkbox" name="onoffswitch3" class="onoffswitch3-checkbox" id="myonoffswitch3" checked>
    <label class="onoffswitch3-label" for="myonoffswitch3">
        <span class="onoffswitch3-inner">
            <span class="onoffswitch3-active">
                <marquee class="scroll-text"> Community Members Rates:₦25k -business name registration,₦50k -company incorporation, ₦50k -trademark registration, ₦55k -textile/non-textile design registration, from ₦80k convention and non-convention patent registration <span class="glyphicon glyphicon-forward"></span>Direct Image printers and ID printers are now available in the categories from ₦200k  <span class="glyphicon glyphicon-forward"></span> NCC Class C filing - ₦30,000 (Hire a Freelancer today) WhatsApp: 07055620001 <span class="glyphicon glyphicon-forward"></span>Hire Drivers: Hire freelance or full-time drivers with backround checked from ₦40k <span class="glyphicon glyphicon-forward"></span> Buy HP Stream - 11-ah006na at less ₦60k <span class="glyphicon glyphicon-forward"></span>  Hire Aluminium fabricators or buy aluminium casement window for ₦45k <span class="glyphicon glyphicon-forward"></span>Hire freelance writers and researchers at a reasonable fees <span class="glyphicon glyphicon-forward"></span>Hire Mechanics:<span class="glyphicon glyphicon-forward"></span>Sotware Developers Here! - call 07055620001 </marquee>
                <span class="onoffswitch3-switch">BREAKING NEWS <span class="glyphicon glyphicon-remove"></span></span>
            </span>
            <span class="onoffswitch3-inactive"><span class="onoffswitch3-switch">SHOW BREAKING NEWS</span></span>
        </span>
    </label>
</div>

app/views/layouts/_contact.html.erb
<div class='container' style="position:relative" id='pulldown'>
  <%= form_with(model: Contact.new, local: true)  do |form| %>
  

  <div class="form-group">
   
    <%= form.text_field :first_name,  autofocus: true, autocomplete: "First Name", placeholder: 'First Name', class: "form-control" %>
  </div>

  <div class="form-group">
  
    <%= form.text_field :last_name,  autofocus: true, autocomplete: "Last Name", placeholder: 'Last Name', class: "form-control" %>
  </div>

  <div class="form-group">
 
    <%= form.text_field :email_address,  autofocus: true, autocomplete: "email", placeholder: 'email', class: "form-control" %>
  </div>

  <div class="form-group">
  
    <%= form.text_field :phone_number,  autofocus: true, autocomplete: "Your Phone Number", placeholder: 'Your Phone Number', class: "form-control" %>
  </div>

  <div class="form-group">
  
    <%= form.text_area :body,  autofocus: true, autocomplete: "Order Details", placeholder: 'Order Details', class: "form-control" %>
  </div>

  <div class="form-group">
    <div class="form-group honeypot">
    <%= label_tag :content %>
    <%= text_field_tag :content, nil, tabindex: '-1' %>
    <span class="help">Do not fill in this field. It is an anti-spam measure.</span>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

  
</div>

app/views/layouts/_featuredpartners.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js"></script>

<div class="container">
 
  <h1 id=" featured"  class="text-capitalize text-center">Featured Partners </h1>
   <section class="customer-logos slider">
    
       
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/automechanic_ronix.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/alunimium_bsolu.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/software_developers!.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/mbi1.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/kpwears_tailoring.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/peter.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/Business.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/D-Computers+Computer+Village+Lagos.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/ola_tailor1.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/diprinter_p.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/list_here.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/WhatsAps_07055620001.jpg"></div>
      <div class="slide"><img src="https://babanla.s3.us-east-2.amazonaws.com/assets/featured/idera_printers.jpg"></div>
   </section>
   

</div>


<script>
    $(document).ready(function(){
    $('.customer-logos').slick({
        slidesToShow: 4,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
        arrows: false,
        dots: false,
        pauseOnHover: false,
        responsive: [{
            breakpoint: 768,
            settings: {
                slidesToShow: 3
            }
        }, {
            breakpoint: 520,
            settings: {
                slidesToShow: 1
            }
        }]
    });
});
</script>

app/views/layouts/_footer.html.erb
<!--<footer class="ct-footer text-center-sm text-center-xs " >-->
    <!--        <div class="container-fluid">-->
    <!--             <div class="container-fluid">-->
    <!--    <div class="row">-->
    <!--        <div class="col-md-3 col-lg-4 col-xl-3">-->
    <!--            <h5 class="btn btn-danger">About</h5>-->
    <!--            <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">-->
    <!--            <p class="mb-0">-->
    <!--                Akobe Limited is an online retail store. Customers  are to bargain for products & Services listed. <br> Concession are always given to customers.-->
    <!--            </p>-->
    <!--        </div>-->

           
    <!--        <div class="col-md-4 col-lg-3 col-xl-3">-->
    <!--            <h5 class="btn btn-danger">Contact</h5>-->
    <!--            <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">-->
    <!--            <ul class="list-unstyled">-->
    <!--                <li class="mb-0"><i class="fa fa-home mr-2" ></i> Akobe Limited</li>-->
    <!--                <li class="mb-0"><i class="fa fa-envelope mr-2"></i> akobelimited@gmail.com</li>-->
    <!--                <li class="mb-0"><i class="fa fa-phone mr-2"></i> + 234 811 333 6667</li>-->
    <!--                <li class="mb-0"><i class="fa fa-print mr-2"></i> + 234 705 562 0001</li>-->
    <!--            </ul>-->
    <!--        </div>-->
            
    <!--         <div class="col-md-4 col-lg-3 col-xl-3">-->
    <!--            <h5 class="btn btn-danger">Services</h5>-->
    <!--            <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">-->
    <!--            <ul class="list-unstyled">-->
    <!--                <li><i class="fa fa-home mr-2"></i> Sell Products</li>-->
    <!--                <li><i class="fa fa-envelope mr-2"></i> Sell Services</li>-->
    <!--                <li><i class="fa fa-phone mr-2"></i> Sell Business</li>-->
    <!--                <li><i class="fa fa-print mr-2"></i> Sell Research</li>-->
    <!--            </ul>-->
    <!--        </div>-->
            
          
    <!--        <div class="col-md-4 col-lg-3 col-xl-3">-->
    <!--            <h5 class="btn btn-danger">Address</h5>-->
    <!--            <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">-->
    <!--            <ul class="list-unstyled">-->
                    
    <!--                <li><i class="fa fa-envelope mr-2"></i> 15, Shasha Road</li>-->
    <!--                <li><i class="fa fa-home mr-2"></i> Opp. Zenith BAnk Beside KFC</li>-->
    <!--                <li><i class="fa fa-phone mr-2"></i> Akowonjo</li>-->
    <!--                <li><i class="fa fa-print mr-2"></i> Lagos</li>-->
                    
    <!--            </ul>-->
    <!--        </div>-->
    <!--        <div class="col-12 copyright mt-3">-->
    <!--            <p class="float-left">-->
    <!--                <a href="#">Back to top</a>-->
    <!--            </p>-->
    <!--            <p class="text-right text-muted">created with <i class="fa fa-heart"></i> by <a href=><i>hardskillshub</i></a> | <span>v. 1.0</span></p>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--</div>-->
               
           
        <!--        <div class="container-fluid">-->
        <!--            <div class="row">-->
        <!--                <div class="col-sm-6 col-lg-2 text-center-md text-center-bg text-center-xs hidden-md">-->
                            
        <!--                  <h4 class="btn btn-warning"> AKOBE </h4>-->
        <!--                </div>-->
        <!--                <div class="col-sm-6 col-md-4 text-center ct-u-paddingTop0">-->
        <!--                    <p class="mb-0">-->
        <!--                        © 2019 Akobe Limited. All Rights Reserved.-->
        <!--                    </p>-->
        <!--                </div>-->
        <!--                <div class="col-sm-6 col-md-5 col-lg-4 text-center ct-u-paddingTop0">-->
        <!--                    <ul class="list-unstyled" >-->
                                
        <!--                        <li class="mb-0"><i class="fa fa-home mr-2" ></i> 15, Shasha Road Akowonjo Lagos</li>-->
        <!--             <li class="mb-0"><i class="fa fa-envelope mr-2"></i> akobelimited@gmail.com</li>-->
        <!--            <li class="mb-0"><i class="fa fa-print mr-2"></i> + 234 705 562 0001</li>-->
                                
        <!--                    </ul>-->
        <!--                </div>-->
        <!--                <div class="col-sm-6 col-md-3 col-lg-2 text-right text-center-md text-center-sm text-center-xs ct-u-paddingTop0">-->
        <!--                    <p>-->
        <!--                        Powered by <a href="//www.akobe.org" target="_blank">Akobe</a>-->
        <!--                    </p>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        </div>-->
           
        <!--</footer>-->

<hr/>
<div class="container">

 
        <div class="text-center center-block">
                            <p class="mb-0">
                                © 2020 Akobe Limited. All Rights Reserved. 15, Shasha Road Akowonjo Lagos. + 234 705 562 0001
                            </p>
                                        
            <br />
                <a href="https://www.facebook.com/akobelimited/"><i class="fa fa-facebook-square fa-3x social"></i></a>
	            <a href="https://twitter.com/AkobeLimited"><i class="fa fa-twitter-square fa-3x social"></i></a>
	            <!--<a href="https://plus.google.com/+Bootsnipp-page"><i class="fa fa-google-plus-square fa-3x social"></i></a>-->
	            <a href="mailto:akobelimited@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>
	         
</div>
    <hr />
</div>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   

    <!-- Bootstrap core CSS -->

<div class="container">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-primary ">
         <%= link_to "AKOBE LIMITED", root_path, id: "prov", class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <!--<h4><li class="nav-item">-->
                    <%#= link_to "See Freelancers", root_path, id: "prov", class: 'navbar-brand' %>
                  
                <!--</li></h4>-->
               <!--<h4> <li class="nav-item">-->
                     <%#= link_to "See Retailers", category_products_path, id: "prov", class: 'navbar-brand' %>
                <!--</li></h4>-->
                <!--<li class="nav-item">-->
                <!--   <%#= link_to "News", people_ticker_path, id: "prov", class: 'navbar-brand' %>-->
                <!--</li>-->
                <!--<li class="nav-item">-->
                <!--   <%#= link_to "Sell", new_post_path, id: "prov", class: 'navbar-brand' %>-->
                <!--</li>-->
                
               <!--<h4> <li class="nav-item">-->
                    <!--<a class="navbar-brand" href="https://form.myjotform.com/seyepet/wholesale-purchase-order-form">Order Now </a>-->
                <!--</li></h4>-->
                <li class="nav-item">
                    <%= link_to "Please Click to Describe your Project", home_index_path, id: "contactus", class: 'btn btn-danger btn-outline-success  btn-block text-monospace font-italic responsive-width' %>
                </li>
            </ul>

<%#= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <!--<div class="input-group">  -->
    <%#= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
  <!--  <div class="input-group-btn">  -->
      <%#= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
  <!--  </div>  -->
  <!--</div>  -->
<%# end %>



        
            <!--<div class="container">-->
                <%#= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-right') do %>  
  <!--<div class="input-group">  -->
  <!--  <%#= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  -->
  <!--  <div class="input-group-btn">  -->
  <!--    <%#= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  -->
  <!--  </div>  -->
  <!--</div>  -->
<%# end %>
    
	<!--<div class="row justify-content-center">-->
 <!--                       <div class="col-12 col-md-10 col-lg-8">-->
 <!--                           <form class="card card-sm">-->
 <!--                               <div class="card-body row no-gutters align-items-center">-->
 <!--                                   <div class="col-auto">-->
 <!--                                       <i class="fas fa-search h4 text-body"></i>-->
 <!--                                   </div>-->
                                    <!--end of col-->
 <!--                                   <div class="col">-->
 <!--                                       <input class="form-control form-control-lg form-control-borderless" type="search" placeholder="Search products or keywords">-->
 <!--                                   </div>-->
                                   
                                    <!--end of col-->
 <!--                                   <div class="col-auto">-->
                                        
 <!--                                   </div>-->
                                    <!--end of col-->
 <!--                               </div>-->
 <!--                           </form>-->
 <!--                       </div>-->
                        <!--end of col-->
 <!--                   </div>-->
<!--</div>-->



            <!--<form class="form-inline my-2 my-lg-0">-->
                <!--<div class="input-group input-group-sm">-->
                <!--    <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm" placeholder="Search...">-->
                <!--    <div class="input-group-append">-->
                        <!--<button type="button" class="btn btn-secondary btn-number">-->
                        <!--    <%#= form_tag(root_path, method: :get) do %>-->
                        <!--       <%#= text_field_tag :term, params[:term] %>-->
                        <!--           <%#= submit_tag 'Search', name: nil, class: 'btn btn-secondary btn-number' %>-->
                        <!--            <%# end %>-->
                        <!--    <i class="fa fa-search"></i>-->
                        <!--</button>-->
                <!--    </div>-->
                <!--</div>-->
                <!--<%#= form_tag(root_path, method: :get) do %>-->
                <!--               <%#= text_field_tag :term, params[:term] %>-->
                <!--                   <%#= submit_tag 'Search', name: nil, class: 'btn btn-secondary btn-number' %>-->
                <!--                    <%# end %>-->
                   
                <!--<li class="nav-item" style="list-style: none;">-->
                <!--<a href="https://www.linkedin.com/company/13063462/" class="fa fa-linkedin"></a>-->
                <!--</li>-->
                   <% if user_signed_in? %>-->
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand'  %>
                <% else %>
                  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-brand'  %> 
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-brand'  %>
                <% end %>
                <!--</a>-->
            <!--</form>-->
        </div>
    </div>
</nav>


 

  
 <!--<div class="secondnavbar" class="container-fluid">-->
  
 <!--         <body id="2navbar">-->
 <!--               <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">-->
 <!--             <h4 class="my-0 mr-md-auto font-weight-normal">Akobe Limited</h4>-->
 <!--             <nav class="my-2 my-md-0 mr-md-3">-->
 <!--             <a class="p-2 text-dark" href="">08113336667</a>-->
 <!--               <a class="p-2 text-dark" href="">akobelimited@gmail.com</a>-->
 <!--              <a class="p-2 text-dark" href="">Support</a>-->
 <!--                <%#= link_to "Blog", root_path, id: "prov" %>-->
 <!--             <%#= link_to "Pricing", root_path, id: "prov" %>-->
              
 <!--             </nav>-->
              
 <!--             <p class="navbar-text pull-right">-->
 <!--               <%# if user_signed_in? %>-->
 <!--                 Logged in as <strong><%#= current_user.email %></strong>.-->
 <!--                 <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |-->
 <!--                 <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>-->
 <!--               <%# else %>-->
 <!--                 <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |-->
 <!--                 <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>-->
 <!--               <%# end %>-->
 <!--               </p>-->
 <!--       </div>-->
 <!--       </div>-->
 <!--   </div>-->



<!--<div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-auto mb-9">-->
<!--             <div class="card" class="justify-content-center" styles="width: auto";>-->
<!--              <div class="card-header">-->
<!--                <h3>Service Categories (<%#= @categories.length %>)</h3>-->
<!--              </div>-->
<!--              <%# @categories.each do |category| %>-->
<!--              <ul class="list-group list-group-flush">-->
<!--                <%#= link_to category_products_path(category) do %>-->
<!--                <li class="list-group-item"> -->
<!--                <h4><%#= category.title %></h4>-->
<!--               (<%#= category.products_count %> products)-->
<!--              <%# end %></li>-->
            <!--<li class="list-group-item">Dapibus ac facilisis in</li>-->
<!--            <%# end %>-->
<!--          </ul>-->
<!--</div>-->

<!--    </div>-->
    <br />
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Titun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title> Akobe Limited - <%= content_for?(:title) ? yield(:title) : 'We are a Community of Service Providers, Retailers and Freelancers. Community Members offers Reliable Services and Best Quality for the Best Price and also Give Cash Back to the Customers' %> </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
 <script src="https://www.google.com/recaptcha/api.js"  async defer></script>
 <meta name='description'
      content='<%= yield_meta_tag(:description, 'We are a Community of Service Providers, Retailers and Freelancers. Community Members offers Reliable Services and Best Quality for the Best Price and also Give Cash Back to the Customers') %>' />

 
 
     <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-9509071305290324",
    enable_page_level_ads: true
  });
</script>
<%= render partial: "layouts/google_analytics.html.erb" %>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155367779-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155367779-1');
</script>
<%= yield :recaptcha_js %>

</head>

<body>
    
   
    
   
    
    <div class='container'>
       
        <p>
       <%= link_to "Categories", categories_path%>
      <%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>
   </p>
         <%= render 'layouts/header' %>
   
    <%= yield  %>
   
    </div>
    
  </body>
 
</html>
  <%= render 'layouts/footer' %>